version: "3.8"

services: 
  server:
    container_name: abex_iv_backend
    build: .
    command: python ./abexiv/manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/server
    ports: 
      - 8000:8000
    depends_on: 
      - db
  db:
    image: postgres:13
    container_name: abex_iv_postgres
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: