# Generated by Django 4.1 on 2022-09-01 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0002_answer_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='user_id',
            new_name='user',
        ),
    ]
