# Generated by Django 4.1 on 2022-08-31 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_answer_questionanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='question',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='QuestionAnswer',
        ),
    ]
